version: '3.8'

services:

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  config-server:
    build: ./config-server
    ports:
      - "2001:2001"
  service-discovery:
    build: ./service-discovery
    ports:
      - "2000:2000"
    depends_on:
      - config-server
  api-gateway:
    build: ./api-gateway
    ports:
      - "2002:2002"
    depends_on:
      - service-discovery
      - config-server
  customer-service:
    build: ./customer-service
    ports:
      - "2003:2003"
    depends_on:
      - service-discovery
      - config-server
      - postgres
      - redis
  account-service:
    build: ./account-service
    ports:
    - "2004:2004"
    depends_on:
      - service-discovery
      - config-server
      - postgres

  bills-service:
    build: ./bills-service
    ports:
      - "2005:2005"
    depends_on:
      - service-discovery
      - config-server
      - postgres

  transfer-service:
    build: ./transfer-service
    ports:
      - "2006:2006"
    depends_on:
      - service-discovery
      - config-server
      - postgres

  dashboard-service:
    build: ./dashboard-service
    ports:
      - "2007:2007"
    depends_on:
      - service-discovery
      - config-server
      - account-service
      - bills-service
      - transfer-service